name: Create new release

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-slim
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Setup Go 1.26.x
        uses: actions/setup-go@v6
        with:
          go-version: 1.26.x

      - name: Build linux/amd64
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -o "opencast-meet-${{ github.ref_name }}.linux-x86_64"

      - name: Build linux/arm64
        env:
          GOOS: linux
          GOARCH: arm64
        run: go build -o "opencast-meet-${{ github.ref_name }}.linux-arm64"

      - name: Build x86_64 RPM
        env:
          BINARY: "opencast-meet-${{ github.ref_name }}.linux-x86_64"
          ARCH: x86_64
        run: >
          docker run
          -v .:/rpmbuild
          quay.io/centos/centos:stream10
          /rpmbuild/.rpm/build-rpm.sh
          "${BINARY}"
          "${{ github.ref_name }}"
          "${ARCH}"

      - run: file opencast-meet*

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          files: opencast-meet*
          fail_on_unmatched_files: true
          generate_release_notes: true
